name: Linux
on:
  push:
    branches: [ "main", v* ]
  pull_request:
    branches: [ "main", v* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build linux
        run: |
          make linux
        
      - name: Upload Linux x64
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: artifacts/*.tar.gz