name: Windows
on:
  push:
    branches: [ "main", v* ]
  pull_request:
    branches: [ "main", v* ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x

      - name: Build Windows
        shell: pwsh
        run: |
          .\buildWindows.ps1
        
      - name: Upload Windows x64
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: artifacts/BSkyOAuthTokenGenerator.zip